import React, { useState, useEffect } from 'react';
import { 
  FileText, 
  Download, 
  Printer, 
  ShieldCheck, 
  ShieldAlert, 
  Calendar, 
  Activity,
  CheckCircle2,
  RefreshCw,
  ExternalLink
} from 'lucide-react';
import { api } from '../services/api';
import ThreatBadge from '../components/ThreatBadge';

export const Reports = () => {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);

  const fetchReport = async () => {
    setLoading(true);
    try {
      const res = await api.getReport();
      setReport(res);
    } catch (err) {
      console.error("Failed to load report:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReport();
  }, []);

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadCsv = () => {
    window.open(api.getReportCsvUrl(), '_blank');
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[70vh]">
        <div className="flex flex-col items-center gap-3">
          <div className="w-8 h-8 border-4 border-cyan-500/20 border-t-cyan-500 rounded-full animate-spin"></div>
          <p className="text-xs font-mono text-cyan-400 animate-pulse">Compiling Executive SOC Security Report...</p>
        </div>
      </div>
    );
  }

  const metrics = report?.metrics || {
    total_events: 0,
    total_attacks: 0,
    critical_threats: 0,
    high_threats: 0,
    normal_traffic: 0,
    detection_rate: 0
  };

  return (
    <div className="p-6 space-y-6 max-w-6xl mx-auto">
      {/* Top Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 glass-card p-4 rounded-xl border border-slate-800 print:hidden">
        <div>
          <h2 className="text-base font-bold font-mono text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-400" />
            Executive SOC Threat Intelligence Report
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Audit-grade cybersecurity evaluation generated by DeepFusionGuard AI pipeline.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <button
            onClick={handleDownloadCsv}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-mono font-semibold shadow-md shadow-emerald-600/20 transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download CSV</span>
          </button>
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-mono font-semibold shadow-md shadow-cyan-600/20 transition-all cursor-pointer"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print / Save PDF</span>
          </button>
        </div>
      </div>

      {/* Printable Report Document Card */}
      <div className="glass-card rounded-2xl border border-slate-800 p-8 space-y-8 print:border-none print:bg-white print:text-black">
        {/* Report Header */}
        <div className="border-b border-slate-800 pb-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2.5 mb-1.5">
              <span className="text-xl font-black tracking-wider text-white font-mono">
                DEEP<span className="text-cyan-400">FUSION</span>GUARD
              </span>
              <span className="text-xs font-mono px-2 py-0.5 rounded bg-cyan-950 text-cyan-400 border border-cyan-800">
                AUDIT CERTIFIED
              </span>
            </div>
            <p className="text-xs text-slate-400 font-mono">
              Multi-Modal Cyber Attack Detection & Topological Threat Assessment
            </p>
          </div>

          <div className="text-left sm:text-right text-xs font-mono space-y-1 text-slate-400">
            <p><span className="text-slate-400">Report ID:</span> <span className="text-cyan-400 font-bold">{report?.report_id}</span></p>
            <p><span className="text-slate-400">Timestamp:</span> <span className="text-slate-200">{report?.generated_at}</span></p>
            <p><span className="text-slate-400">Evaluation Mode:</span> <span className="text-emerald-400 font-semibold">Random Forest + GNN Fusion</span></p>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="p-5 rounded-xl bg-slate-900/80 border border-slate-800/80 space-y-2">
          <h3 className="text-xs font-bold font-mono uppercase tracking-wider text-cyan-400 flex items-center gap-2">
            <Activity className="w-4 h-4" />
            Executive Summary
          </h3>
          <p className="text-sm text-slate-200 leading-relaxed font-sans">
            {report?.executive_summary}
          </p>
        </div>

        {/* Key Telemetry Metrics */}
        <div>
          <h3 className="text-xs font-bold font-mono uppercase tracking-wider text-slate-400 mb-3">
            Core Incident Metrics
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 font-mono">
            <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800">
              <span className="text-xs text-slate-400">Total Telemetry Flows</span>
              <p className="text-2xl font-bold text-slate-100 mt-1">{metrics.total_events}</p>
            </div>
            <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800">
              <span className="text-xs text-slate-400">Confirmed Attacks</span>
              <p className="text-2xl font-bold text-rose-400 mt-1">{metrics.total_attacks}</p>
            </div>
            <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800">
              <span className="text-xs text-slate-400">Critical Threat Vectors</span>
              <p className="text-2xl font-bold text-purple-400 mt-1">{metrics.critical_threats}</p>
            </div>
            <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800">
              <span className="text-xs text-slate-400">Threat Detection Rate</span>
              <p className="text-2xl font-bold text-cyan-400 mt-1">{metrics.detection_rate}%</p>
            </div>
          </div>
        </div>

        {/* Attack Breakdown Table */}
        {report?.attack_statistics && report.attack_statistics.length > 0 && (
          <div>
            <h3 className="text-xs font-bold font-mono uppercase tracking-wider text-slate-400 mb-3">
              Attack Classification Breakdown
            </h3>
            <div className="overflow-x-auto rounded-xl border border-slate-800">
              <table className="w-full text-left text-xs font-mono">
                <thead className="bg-slate-900 border-b border-slate-800 text-slate-400">
                  <tr>
                    <th className="p-3">Attack Class</th>
                    <th className="p-3">Incidents Logged</th>
                    <th className="p-3">Average Fused Risk</th>
                    <th className="p-3">MITRE Reference</th>
                    <th className="p-3">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/60">
                  {report.attack_statistics.map((stat, idx) => (
                    <tr key={idx} className="hover:bg-slate-900/40">
                      <td className="p-3">
                        <ThreatBadge type={stat.type} />
                      </td>
                      <td className="p-3 font-bold text-slate-200">{stat.count}</td>
                      <td className="p-3 text-cyan-400 font-bold">{Math.round(stat.avg_risk * 100)}%</td>
                      <td className="p-3 text-slate-400">
                        {stat.type === 'DoS' ? 'T1498 (Network Flooding)' : 
                         stat.type === 'Probe' ? 'T1046 (Port Scanning)' :
                         stat.type === 'R2L' ? 'T1110 (Brute Force)' : 'T1068 (Privilege Escalation)'}
                      </td>
                      <td className="p-3">
                        <span className="text-emerald-400 font-semibold flex items-center gap-1">
                          <CheckCircle2 className="w-3.5 h-3.5" />
                          Contained
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Recent High-Priority Incidents */}
        {report?.recent_attacks && report.recent_attacks.length > 0 && (
          <div>
            <h3 className="text-xs font-bold font-mono uppercase tracking-wider text-slate-400 mb-3">
              Recent High-Priority Interceptions
            </h3>
            <div className="space-y-2">
              {report.recent_attacks.slice(0, 5).map((atk) => (
                <div key={atk.id} className="p-3.5 rounded-lg bg-slate-900/50 border border-slate-800 text-xs font-mono flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <ThreatBadge type={atk.attack_type} />
                    <span className="font-bold text-rose-400">{atk.source_ip}</span>
                    <span className="text-slate-500">→</span>
                    <span className="text-slate-300">{atk.destination_ip}</span>
                    <span className="text-slate-500">({atk.protocol}/{atk.service})</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-cyan-400 font-bold">Conf: {Math.round(atk.ml_confidence)}%</span>
                    <ThreatBadge type={atk.severity} variant="severity" />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Compliance Footer */}
        <div className="pt-6 border-t border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs font-mono text-slate-500">
          <span>Framework: {report?.framework_compliance?.mitre_framework}</span>
          <span>SOC System Clearance: Verified Level 4 Defense</span>
        </div>
      </div>
    </div>
  );
};

export default Reports;
